# NOTE: This pre-commit configuration is meant for the JuliaFormatter repo itself.
# Do not use this config in your own repositories! Instead, see
# https://juliaeditorsupport.github.io/JuliaFormatter.jl/stable/precommit/
repos:
- repo: local
  hooks:
  - id: julia-formatter
    name: "Julia Formatter"
    entry: "jlfmt --inplace"
    pass_filenames: true
    always_run: false
    types: [file]
    files: \.(jl|[jq]?md)$
    exclude: '^(test/|\.github/)'
    language: "system"
-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes
